/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fcf8fa',
        'surface-bright': '#fcf8fa',
        'secondary-container': '#2170e4',
        'tertiary-fixed': '#fcdeb5',
        'inverse-on-surface': '#f3f0f2',
        'secondary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#131b2e',
        'inverse-primary': '#bec6e0',
        'on-error-container': '#93000a',
        'surface-container': '#f0edef',
        'on-secondary': '#ffffff',
        'tertiary-container': '#271901',
        'on-tertiary-fixed': '#271901',
        'on-secondary-container': '#fefcff',
        'primary-fixed-dim': '#bec6e0',
        error: '#ba1a1a',
        'surface-dim': '#dcd9db',
        'on-tertiary-fixed-variant': '#574425',
        primary: '#000000',
        'tertiary-fixed-dim': '#dec29a',
        'on-tertiary': '#ffffff',
        'surface-container-low': '#f6f3f5',
        'inverse-surface': '#303032',
        secondary: '#0058be',
        'on-error': '#ffffff',
        'on-secondary-fixed': '#001a42',
        'surface-variant': '#e4e2e4',
        'on-surface': '#1b1b1d',
        'surface-tint': '#565e74',
        'primary-container': '#131b2e',
        'on-primary': '#ffffff',
        'on-background': '#1b1b1d',
        outline: '#76777d',
        'error-container': '#ffdad6',
        'on-surface-variant': '#45464d',
        'on-primary-fixed-variant': '#3f465c',
        'secondary-fixed': '#d8e2ff',
        tertiary: '#000000',
        'outline-variant': '#c6c6cd',
        'on-primary-container': '#7c839b',
        'surface-container-highest': '#e4e2e4',
        'primary-fixed': '#dae2fd',
        'on-tertiary-container': '#98805d',
        background: '#fcf8fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#eae7e9',
        'on-secondary-fixed-variant': '#004395',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'reading-width': '720px',
        xl: '48px',
        'container-max': '1140px',
        lg: '24px',
        gutter: '24px',
        unit: '4px',
        sm: '8px',
        xs: '4px',
        md: '16px',
        xxl: '80px',
      },
      fontFamily: {
        h3: ['Newsreader'],
        'body-lg': ['Newsreader'],
        'nav-link': ['Manrope'],
        'body-md': ['Manrope'],
        h1: ['Newsreader'],
        h2: ['Newsreader'],
        'label-sm': ['Manrope'],
      },
      fontSize: {
        h3: ['24px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-lg': ['20px', { lineHeight: '1.7', fontWeight: '400' }],
        'nav-link': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        h1: ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        h2: ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
